### PR TITLE
Samplebranch

### PR DESCRIPTION
**Pull request by Purushothaman1962**
Verify my program to merge.

### CODE REVIEW

**Review by ARAVIND472A — COMMENTED** [review]
1. Purushoth kindly verify that in the Movie.java change the variable name and remove the comment Todo.
2. In MovieDAO.java remove the unused import statement List and Query.
3. In MMSController.java modify the method name from PerformUpdate to performUpdate

**Comment by Purushothaman1962** [comment]
Yes Aravind, I have updated it. Kindly verify it.

**Comment by ARAVIND472A** [comment]
Yes, Now it is fine you can merge.

**Comment by Purushothaman1962** [comment]
Thank you

**Pull request merged**
